import { environment } from '../../../environments/environment.prod';

/**server end points */
// const baseUrl = environment.SA_URL;
// const API_URL = environment.B2C_URL;
// const B2B_URL = environment.B2B_URL;
const proj1 = '/b2b';
const proj2 = '/supervision';

const baseUrl = 'http://49.50.99.196:4032';
const B2B_URL = 'http://49.50.99.196:4038';
const API_URL = 'http://49.50.99.196:4035';
/* please maintain Ascending Order of the keys*/
export const apiMap = {
  agentDetails: `${baseUrl + proj1}/user/service/AgentDetails`,
  activate: `${B2B_URL + proj1}/user/service/activate`,
  bankDetails: `${baseUrl + proj1}/transaction/service/BankDetails`,
  bankAccountDetails: `${baseUrl + proj2}/cms/service/BankAccountDetails`,
  balanceManager: `${baseUrl + proj1}/transaction/service/BalanceManager`,
  banalanceTransferTypes: `${baseUrl + proj1}/transaction/service/BanalanceTransferTypes`,
  bookingCalender: `${B2B_URL + proj1}/reports/travelCalendar`,
  bookingDetails: `${baseUrl + proj1}/transaction/service/BookingDetails`,
  cabinClass: baseUrl + '/flight/service/CabinClass',
  changePassword: `${baseUrl + proj1}/user/service/ChangePassword`,
  creditLimitManager: `${baseUrl + proj1}/transaction/service/CreditLimitManager`,
  creditLimitRequest: `${baseUrl + proj1}/transaction/service/CreditLimitRequest`,
  dailySalesReport: `${baseUrl + proj1}/flight/service/DailySalesReport`,
  domainLogo: `${baseUrl + proj1}/user/service/DomainLogo`,
  uploadPassportVisa: `${baseUrl + proj1}/uploadPassportVisa`,
  editProfile: `${baseUrl + proj1}/user/service/EditProfile`,
  emailVoucher: `${baseUrl + proj1}/voucher/service/EmailVoucher`,
  extraServices: baseUrl + '/flight/service/ExtraServices',
  eventNotfications: `${baseUrl + proj1}/transaction/service/EventNotfications`,
  flightVoucher: `${baseUrl + proj1}/voucher/service/FlightVoucher`,
  latestTransactions: `${baseUrl + proj1}/transaction/service/LatestTransactions`,
  latestEventNotfications: `${baseUrl + proj1}/transaction/service/LatestEventNotfications`,
  moduleBookingCount: `${baseUrl + proj1}/transaction/service/ModuleBookingCount`,
  monthlyRecapReport: `${baseUrl + proj1}/transaction/service/MonthlyRecapReport`,
  registration: `${B2B_URL + proj1}/user/service/register`,
  setBalanceAlert: `${baseUrl + proj1}/transaction/service/SetBalanceAlert`,
  updateBalanceAlert: `${baseUrl + proj1}/transaction/service/UpdateBalanceAlert`,
  updateDomainLogo: `${baseUrl + proj1}/user/service/UpdateDomainLogo `,
  updateMarkup: `${baseUrl + proj1}/voucher/service/UpdateMarkup`,
  updateAgent: `${B2B_URL + proj1}/usermanagement/updateAgent`,
  userLogin: `${B2B_URL + proj1}/user/service/UserLogin`,
  validateOTP: `${B2B_URL + proj1}/user/service/validateOTP`,
  updateProfile: `${baseUrl + proj1}/user/service/UpdateProfile`,
  userLogout: `${baseUrl + proj1}/user/service/UserLogout`,
  currencyList: `${baseUrl}/flight/service/CurrencyList`,
  sendItinerary: `${API_URL}/webservice/flight/sendItinerary`,
  airportList: `${API_URL}/webservice/flight/autocomplete`,
  preferredAirlines: `${B2B_URL}/b2b/flight/service/preferredAirlines`,
  search: `${API_URL}/webservice/flight/search`,
  updateFareQuote: `${API_URL}/webservice/flight/fareQuote`,
  commitBooking: `${API_URL}/webservice/flight/commitBooking`,
  finalBooking: `${API_URL}/webservice/flight/reservation`,
  currencyConversionRate: `${API_URL}/webservice/flight/CurrencyConversionRate`,
  flightType: `${API_URL}/webservice/flight/flightType`,
  agentAccountLedger: `${B2B_URL}/b2b/reports/accountLedger`,
  transactionLogs: `${B2B_URL}/b2b/reports/transactionLogs`,
  balanceRequest: `${B2B_URL}/b2b/reports/balanceRequest`,
  agentActivate: `${B2B_URL}/b2b/user/service/activate`,
  refreshToken: `${baseUrl}/sa/auth/service/refreshToken`,
  countryList: `${baseUrl}/sa/common/CountryList`,
  fareRule: `${API_URL}/webservice/flight/fareRule`,
  markupReport: `${B2B_URL + proj1}/core/core-markup/markupList`,
  markupList: `${B2B_URL}/b2b/core/core-markup/markupList`,
  addMarkup: `${B2B_URL + proj1}/core/core-markup/addMarkup`,
  deleteMarkup: `${B2B_URL}/b2b/core/core-markup/deleteMarkup`,
  updateFlightMarkup: `${B2B_URL + proj1}/core/core-markup/updateMarkupList`,
  flightReports: `${B2B_URL + proj1}/reports/flightReport`,
  hotelReports: `${B2B_URL + proj1}/reports/hotelReport`,
  carReports: `${B2B_URL + proj1}/reports/carReport`,
  bookingReports: `${B2B_URL + proj1}/flight/service/BookingReports`,
  subAgentList: `${B2B_URL + proj1}/usermanagement/subAgentList`,
  userTitlelist: `${B2B_URL + proj1}/common/UserTitleList`,
  addSubAgent: `${B2B_URL + proj1}/usermanagement/addSubAgent`,
  updateSubAgent: `${B2B_URL + proj1}/usermanagement/updateSubAgent`,
  travellerManagementList: `${B2B_URL + proj1}/travellerManagement/travellerManagementList`,
  addTravellerManagement: `${B2B_URL + proj1}/travellermanagement/addTravellerManagement`,
  updateTravellerManagement: `${B2B_URL + proj1}/travellermanagement/updateTravellerManagement`,
  autoCompleteEmail: `${B2B_URL + proj1}/travellermanagement/autoComplete`,
  getAgentLoginAlert: `${baseUrl}/sa/core/core-agent-login-alert/getAgentLoginAlert`,
  addCoreHelpdesk: `${B2B_URL + proj1}/core/core-helpdesks/addCoreHelpdesk`,
  coreHelpdeskList: `${B2B_URL + proj1}/core/core-helpdesks/coreHelpdeskList`,
  updateLogouttime: `${B2B_URL + proj1}/user/service/updateLogoutDateTime`,
  staticPageContentsList: `${B2B_URL + proj1}/common/staticPageContentsList`,
  sliderSettingsList: `${B2B_URL + proj1}/common/sliderSettingsList`,
  agentSubAgentFlightCounts: `${B2B_URL + proj1}/common/bookings/agentSubAgentFlightCounts`,
  getAgentSubAgentTotalLoginDetails: `${B2B_URL + proj1}/common/bookings/getAgentSubAgentTotalLoginDetails`,
  uploadUserProfilePhoto: `${B2B_URL + proj1}/usermanagement/uploadUserProfilePhoto`,
  updateLostBaggageProtectionPrice: `${API_URL}/webservice/flight/updateLostBaggageProtectionPrice`,
  baggageproductList: `${B2B_URL}/b2b/baggageInsurance/productList`,
  pnrRetrieve: `${API_URL}/webservice/flight/pnrRetrieve`,
  checkWalletBalance: `${B2B_URL}/b2b/account-system/checkWalletBalance`,
  deductFromWallet: `${B2B_URL}/b2b/account-system/deductFromWallet`,
  cancelFlightBooking: `${API_URL}/webservice/flight/cancellation`, //Added by Asha Swamy 17-09-2021
  voidFlightBooking: `${API_URL}/webservice/flight/void`, //Added by Asha Swamy 25-01-2022
  transactionLogsAccountSys: `${B2B_URL}/b2b/account-system/transactionLogs`,
  setBalanceAlertAccountSys: `${B2B_URL}/b2b/account-system/setBalanceAlert`,
  updateBalanceAlertAccountSys: `${B2B_URL}/b2b/account-system/updateBalanceAlert`,
  accountLedgerAccountSys: `${B2B_URL}/b2b/account-system/accountLedger`,
  balanceRequestAccountSys: `${B2B_URL}/b2b/account-system/balanceRequest`,
  balanceRequestListAccountSys: `${B2B_URL}/b2b/account-system/balanceRequestList`,
  creditLimitRequestAccountSys: `${B2B_URL}/b2b/account-system/creditLimitRequest`,
  creditLimitRequestListAccountSys: `${B2B_URL}/b2b/account-system/creditLimitRequestList`,
  listBankAccountAccountSys: `${B2B_URL}/b2b/cms/cms-bankaccounts/listBankAccount`,
  getAgentById: `${B2B_URL}/b2b/usermanagement/getAgentById`,
  commissionList: `${B2B_URL}/b2b/core/core-commission/commissionList`,
  getRequestTypes: `${B2B_URL}/b2b/common/getRequestTypes`,
  getModuleTypes: `${B2B_URL}/b2b/common/getModuleTypes`,
  phoneCodeList: `${B2B_URL}/b2b/common/phoneCodeList`,
  getPaymentModes: `${B2B_URL}/b2b/common/getPaymentModes`,
  getDomainLogo: `${B2B_URL}/b2b/common/uploadDomainLogo`,
  cityList: `${API_URL}/webservice/hotel/hotel/autoComplete`,
  searchHotel: `${API_URL}/webservice/hotel/hotel/searchHotels`,
  hotelDetails: `${API_URL}/webservice/hotel/hotel/hotelDetails`,
  blockRoom: `${API_URL}/webservice/hotel/hotel/blockRooms`,
  addPaxDetails: `${API_URL}/webservice/hotel/hotel/addPaxDetails`,
  reservation: `${API_URL}/webservice/hotel/hotel/reservations`,
  hotelVoucher: `${API_URL}/webservice/hotel/hotel/voucher`,
  b2bHotelVouher: `${B2B_URL}/b2b/hotel/service/hotelVoucher`,
  flightApprovalRequest:`${B2B_URL}/b2b/reports/flightApprovalRequest`,
  servicePurchase: `${B2B_URL}/b2b/baggageInsurance/servicePurchase`,
  listFlightTopDestination: `${B2B_URL}/b2b/flight/service/listFlightTopDestination`,
  ManageDomain: `${B2B_URL}/b2b/common/ManageDomain`,
  executePayment: `${B2B_URL}/b2b/paymentGateway/executePayment`,
  executePayment_local: `http://localhost:4008/b2b/paymentGateway/executePayment`,
  b2bFlightVoucher: `${B2B_URL}/b2b/flight/service/flightVoucher`,
  completeBooking: `${API_URL}/webservice/hotel/hotel/completeBooking`,
  completeBooking_dev: `http://localhost:4005/webservice/hotel/hotel/completeBooking`,
  searchByBookindId: `${B2B_URL}/b2b/common/bookings/searchByBookindId`,
  forgotPassword: `${B2B_URL}/b2b/user/service/forgotPassword`,
  updatePassword: `${B2B_URL}/b2b/user/service/updatePassword`,
  resetPassword: `${B2B_URL}/b2b/user/service/resetPassword`,
  notifications: `${B2B_URL}/b2b/logger/service/notifications`,
  activeNotificationCount: `${B2B_URL}/b2b/logger/service/activeNotificationCount`,
  updateViewedNotifications: `${B2B_URL}/b2b/logger/service/updateViewedNotifications`,
  paymentConfirmation: `${B2B_URL}/b2b/flight/service/paymentConfirmation`,
  flightUpdatePNR: `${B2B_URL}/b2b/reports/flightUpdatePNR`,
  reservationResponse: `${API_URL}/webservice/flight/reservationResponse`,
  createAppReference: `${API_URL}/webservice/common/createAppReference`,
  getPrivilegePageList: `${B2B_URL}/b2b/core/core-privilege/getPrivilegePageList`,
  getPrivilegedUser: `${B2B_URL}/b2b/core/core-privilege/getPrivilegedUser`,
  updatePrivilegeAccess: `${B2B_URL}/b2b/core/core-privilege/updatePrivilegeAccess`,
  setUserPrivilege: `${B2B_URL}/b2b/core/core-privilege/setUserPrivilege`,
  revokeParticularPrivilege: `${B2B_URL}/b2b/core/core-privilege/revokeParticularPrivilege`,
  instantRecharge: `${B2B_URL}/b2b/paymentGateway/instantRecharge`,
  sslTransactionInit: `${B2B_URL}/b2b/paymentGateway/sslTransactionInit`,
  activeAirlineHotelPartnersList: `${B2B_URL}/b2b/core/core-airline-hotel-partners/activeAirlineHotelPartnersList`,
  hotelPaymentConfirmation: `${B2B_URL}/b2b/hotel/service/paymentConfirmation`,
  liveFlightInfo: `${B2B_URL}/b2b/flight/service/liveFlightInfo`,
  flightInfo: `${B2B_URL}/b2b/flight/service/flightInfo`,
  flightInvoiceReport: `${B2B_URL + proj1}/reports/flightInvoiceReport`,
  sendInvoice: `${B2B_URL + proj1}/reports/sendInvoice`,
  getPaymentGateWays: `${API_URL}/webservice/paymentGateway/getPaymentGateWays`,
  uploadFlightDocument:`${API_URL}/webservice/flight/documentUpload`,
  importPnr: `${API_URL}/webservice/flight/importPNR`,
  updateWallet:`${B2B_URL}/b2b/account-system/updateWallet`,
  flightSeatAvailability: `${API_URL}/webservice/flight/seatAvailability`,
  // HotelCrs api's
  autoCompleteCrs: `${API_URL}/webservice/hotel/hotel/autoCompleteCrs`,
  hotelQueues:`${baseUrl}/sa/hotel/hotels/hotelQueues`,
  hotelCancel:`${API_URL}/webservice/hotel/hotel/cancelBookingCrs`,
  approvarBooking:`${API_URL}/webservice/common/approvarBooking`,
  approveDetails:`${API_URL}/webservice/common/approveDetails`,
  bookingCount:`${B2B_URL}/b2b/reports/bookingCount`,
  busApprovalRequest: `${B2B_URL}/b2b/reports/busApprovalRequest`, 
  //Bus api's
  busCityList: `${API_URL}/webservice/bus/bus/cityList`,
  searchBus: `${API_URL}/webservice/bus/bus/searchBus`,
  seatLayoutBus: `${API_URL}/webservice/bus/bus/seatLayoutBus`,
  seatBusInfo: `${API_URL}/webservice/bus/bus/seatBusInfo`,
  busAddPaxDetails: `${API_URL}/webservice/bus/bus/addPaxDetails`,
  holdSeatsBus: `${API_URL}/webservice/bus/bus/holdSeatsBus`,
  bookSeats: `${API_URL}/webservice/bus/bus/BookSeats`,
  busVoucher: `${API_URL}/webservice/bus/bus/voucher`,
  busPaymentConfirmation: `${API_URL}/b2b/bus/service/paymentConfirmation`,
  busReport:`${B2B_URL}/b2b/reports/busReport`,
  buscancel:`${API_URL}/webservice/bus/bus/cancelBooking`,
  //Train 
  trainCity: `${B2B_URL}/b2b/train/auto_complete`,
  trainCreate: `${B2B_URL}/b2b/train/create`,
  trainFindAll:`${B2B_URL}/b2b/train/findAll`,
  deleteTrain:`${B2B_URL}/b2b/train/delete`,
  trainVoucher:`${B2B_URL}/b2b/train/trainVoucher`, 
  trainCancel:`${B2B_URL}/b2b/train/cancelBooking`,
  //Car
  carCreate: `${B2B_URL}/b2b/car_enquiry/create`,
  carFindAll: `${B2B_URL}/b2b/car_enquiry/findAll`,
  deleteCar:`${B2B_URL}/b2b/car_enquiry/delete`,
  hotelNames:`${baseUrl}/sa/common/hotelNames`,
  carVoucher:`${B2B_URL}/b2b/car_enquiry/carVoucher`, 
  redirectLogin: `${API_URL}/webservice/icic/redirectLogin`,
  carCancel:`${B2B_URL}/b2b/car_enquiry/cancelBooking`,
  iciciHotelCreate: `${B2B_URL}/b2b/icic/hotel/create`,
  iciciHotelFindAll:`${B2B_URL}/b2b/icic/hotel/findAll`,
  iciciHotelDelete:`${B2B_URL}/b2b/icic/hotel/delete`,
  hotelStates:`${baseUrl}/sa/common/hotelStates`,
  iciciCityList:`${B2B_URL}/b2b/icicCityList/findAll`,
  iciciLocationList:`${B2B_URL}/b2b/icicCityLocationList/findAll`,
  iciciHotelList:`${B2B_URL}/b2b/icicHotelList/findAll`,
  iciciGuestHouseList:`${B2B_URL}/b2b/icicGuestHouseList/findAll`,
  corporateList:`${B2B_URL}/b2b/common/corporateList`,
  addTrainingDetails:`${B2B_URL}/b2b/trainingDetails/create`,
  trainerName:`${B2B_URL}/b2b/trainerName/findAll`,
  trainingName:`${B2B_URL}/b2b/trainingName/findAll`,
  trainingVenue:`${B2B_URL}/b2b/trainingVenue/findAll`,
  trainingDetails:`${B2B_URL}/b2b/trainingDetails/findAll`,
  getPolicy:`${B2B_URL}/b2b/policy/getPolicy`,
  carPendingApprovalBookingList:`${B2B_URL}/b2b/car_enquiry/PendingApprovalBookingList`,
  trainPendingApprovalBookingList:`${B2B_URL}/b2b/train/PendingApprovalBookingList`,
  createTripId:`${B2B_URL}/b2b/trip-details/create`,
  updateTripId:`${B2B_URL}/b2b/trip-details/update`,
  deleteTripId:`${B2B_URL}/b2b/trip-details/delete`,
  getTripIdList:`${B2B_URL}/b2b/trip-details/findAll`,
  dcbLogin:`${API_URL}/webservice/dcb/employeeLogin`,
  validateDCBOTP:`${API_URL}/webservice/dcb/validateOTP`,
  findEmployeeId:`${API_URL}/webservice/dcb/findEmployeeId`,
  feedBack:`${API_URL}/webservice/feedback/create`,
  approvalReservations:`${API_URL}/webservice/hotel/hotel/approvalReservations`,
  flightEmail:`${API_URL}/webservice/flight/flightEmail`,
  hotelEmail:`${API_URL}/webservice/hotel/hotel/hotelMail`,
  razorpayTransactionInit: `${B2B_URL}/b2b/paymentGateway/razorpayTransactionInit`,
  razorpayTransactionStatus :`${B2B_URL}/b2b/paymentGateway/razorpayTransactionStatus`,
  cashfreeTransactionInit :`${B2B_URL}/b2b/paymentGateway/cashfreeTransactionInit`,
  cashfreeTransactionStatus:`${B2B_URL}/b2b/paymentGateway/cashfreeTransactionStatus`
};
