import { environment } from "../../../environments/environment.prod";
const proj2 = "/supervision";
const baseUrl = 'http://49.50.99.196:4032/sa';
const B2B_URL = 'http://49.50.99.196:4038';
const B2C_URL = 'http://49.50.99.196:4035';

/* please maintain Ascending Order of the keys*/
export const apiMap = {
    addManageSMS: baseUrl + "/cms/service/AddManageSMS",
    addBankAccountDetails: baseUrl + "/cms/service/AddBankAccountDetails",
    agentBalanceManager: baseUrl + "/transaction/service/AgentBalanceManager",
    agentCreditLimitManager: baseUrl + "/transaction/service/AgentCreditLimitManager",
    agentList: baseUrl + "/user/service/AgentList",
    agentDetails: baseUrl + "/user/service/AgentDetails",
    agentAccoutCredit: baseUrl + "/transaction/service/AgentAccoutCredit",
    agentAccoutDebit: `${baseUrl}/transaction/service/AgentAccoutDebit`,
    apiCurrencyRateList: `${baseUrl}/cms/service/ApiCurrencyRateList`,
    addCurrencyConversion: baseUrl + "/cms/service/AddCurrencyConversion",
    bankAccountDetails: baseUrl + "/cms/service/BankAccountDetails",
    bookingCalender: baseUrl + "/dashboard/report/travelCalendar",
    bookingDetails: baseUrl + "/transaction/service/BookingDetails",
    bookingReports: baseUrl + "/flight/service/BookingReports",
    cityList: baseUrl + "/common/service/CityList",
    currencyConverison: baseUrl + "/cms/service/CurrencyConversion",
    editUser: baseUrl + "/user/service/EditUser",
    eventNotfications: baseUrl + "/transaction/service/EventNotfications",
    flightVoucher: baseUrl + "/voucher/service/FlightVoucher",
    latestEventNotfications: baseUrl + "/transaction/service/LatestEventNotfications",
    loggedInUserList: baseUrl + "/user/service/LoggedInUserList",
    manageDomain: baseUrl + "/cms/service/ManageDomain",
    manageSMS: baseUrl + "/cms/service/ManageSMS",
    monthlyRecapReport: baseUrl + "/transaction/service/MonthlyRecapReport",
    passengerList: `${baseUrl}/flight/service/PassengerList`,
    processAgentBalance: baseUrl + "/transaction/service/ProcessAgentBalance",
    processAgentCreditLimit:
        baseUrl + "/transaction/service/ProcessAgentCreditLimit",
    searchHistory: baseUrl + "/transaction/service/SearchHistory",
    sEO: baseUrl + "/cms/service/SEO",
    SocialLogin: baseUrl + "/cms/service/SocialLogin",
    transactionLogs: baseUrl + "/transaction/service/TransactionLogs",
    updateApiCurrencyRate: `${baseUrl}/cms/service/UpdateApiCurrencyRate`,
    updateBankAccountDetails: baseUrl + "/cms/service/UpdateBankAccountDetails",
    updateCurrencyConverison: baseUrl + "/cms/service/UpdateCurrencyConversion",
    UpdateDomain: baseUrl + "/cms/service/UpdateDomain",
    updateManageSMS: baseUrl + "/cms/service/UpdateManageSMS",
    updateSEO: baseUrl + "/cms/service/UpdateSEO",
    UpdateSocialLogin: baseUrl + "/cms/service/UpdateSocialLogin",
    updateManageSocialLink: baseUrl + "/core/core-manage-social-links/updateManageSocialLink",
    updateUser: baseUrl + "/user/service/updateUser",
    userLogin: `${baseUrl}/auth/service/userLogin`,
    editProfile: `${baseUrl}/user/service/getUserById`,
    userLogout: `${baseUrl}/auth/service/userLogout`,
    changePassword: `${baseUrl}/auth/service/changePassword`,
    forgotPassword: `${baseUrl}/auth/service/forgotPassword`,
    updatePassword: `${baseUrl}/auth/service/updatePassword`,
    resetPassword: `${baseUrl}/auth/service/resetPassword`,
    hotelTypeList: `${baseUrl}/hotel/hotel-types/hotelTypeList`,
    editHotelType: `${baseUrl}/hotel/hotel-types/editHotelType`,
    addHotelType: `${baseUrl}/hotel/hotel-types/addHotelType`,
    updateHotelType: `${baseUrl}/hotel/hotel-types/updateHotelType`,
    hotelAmenityList: `${baseUrl}/hotel/hotel-amenities/hotelAmenityList`,
    editHotelAmenity: `${baseUrl}/hotel/hotel-amenities/editHotelAmenity`,
    addHotelAmenity: `${baseUrl}/hotel/hotel-amenities/addHotelAmenity`,
    updateHotelAmenity: `${baseUrl}/hotel/hotel-amenities/updateHotelAmenity`,
    roomTypeList: `${baseUrl}/hotel/room-types/roomTypeList`,
    editRoomType: `${baseUrl}/hotel/room-types/editRoomType`,
    addRoomType: `${baseUrl}/hotel/room-types/addRoomType`,
    updateRoomType: `${baseUrl}/hotel/room-types/updateRoomType`,
    roomAmenityList: `${baseUrl}/hotel/room-amenities/roomAmenityList`,
    editRoomAmenity: `${baseUrl}/hotel/room-amenities/editRoomAmenity`,
    addRoomAmenity: `${baseUrl}/hotel/room-amenities/addRoomAmenity`,
    updateRoomAmenity: `${baseUrl}/hotel/room-amenities/updateRoomAmenity`,
    hotelList: `${baseUrl}/hotel/hotels/hotelList`,
    addHotel: `${baseUrl}/hotel/hotels/addHotel`,
    editHotel: `${baseUrl}/hotel/hotels/editHotel`,
    updateHotel: `${baseUrl}/hotel/hotels/updateHotel`,
    getHotelDetail: `${baseUrl}/hotel/hotels/getHotelDetail`,
    addRoom: `${baseUrl}/hotel/hotel-rooms/addHotelRoom`,
    editRoom: `${baseUrl}/hotel/hotels/editHotelRoom`,
    updateRoom: `${baseUrl}/hotel/hotels/updateHotelRoom`,
    getRoomsByHotelId: `${baseUrl}/hotel/hotel-rooms/getRoomsByHotelId`,
    addSeason: `${baseUrl}/hotel/room-seasons/addRoomSeason`,
    editSeason: `${baseUrl}/hotel/room-seasons/editRoomSeason`,
    updateSeason: `${baseUrl}/hotel/room-seasons/updateRoomSeason`,
    seasonList: `${baseUrl}/hotel/room-seasons/roomSeasonList`,
    addPrice: `${baseUrl}/hotel/room-prices/addRoomPrice`,
    editPrice: `${baseUrl}/hotel/room-prices/editRoomPrice`,
    updatePrice: `${baseUrl}/hotel/room-seasons/updateRoomPrice`,
    priceList: `${baseUrl}/hotel/room-seasons/roomPriceList`,
    addCancellationPolicy: `${baseUrl}/hotel/room-cancellation-policies/addRoomCancellationPolicy`,
    editCancellationPolicy: `${baseUrl}/hotel/room-cancellation-policies/editRoomCancellationPolicy`,
    updateCancellationPolicy: `${baseUrl}/hotel/room-cancellation-policies/updateRoomCancellationPolicy`,
    cancellationPolicyList: `${baseUrl}/hotel/room-cancellation-policies/roomCancellationPolicyList`,
    uploadHotelLogo: `${baseUrl}/hotel/hotels/uploadHotelLogo`,
    uploadHotelImage: `${baseUrl}/hotel/hotel-images/addHotelImage`,
    uploadHotelRoomImage: `${baseUrl}/hotel/room-images/addRoomImage`,
    masterLog: `${baseUrl}/master/master-transaction/masterLog`,
    balanceReqList: `${baseUrl}/master/master-transaction/balanceReqList`,
    creditLimitReqList: `${baseUrl}/master/master-transaction/creditLimitReqList`,
    addB2cMarkup: `${baseUrl}/core/core-markup/addB2cMarkup`,
    b2cMarkupList: `${baseUrl}/core/core-markup/b2cMarkupList`,
    preferredAirlines: `${baseUrl}/flight/flight-service/preferredAirlines`,
    b2bMarkupList: `${baseUrl}/core/core-markup/b2bMarkupList`,
    addB2bMarkup: `${baseUrl}/core/core-markup/addB2bMarkup`,
    addBankAccountDetail: `${baseUrl}/cms/cms-bankaccounts/addBankAccountDetail`,
    listBankAccount: `${baseUrl}/cms/cms-bankaccounts/listBankAccount`,
    updateBankAccountContent: `${baseUrl}/cms/cms-bankaccounts/updateBankAccountContent`,
    updateBankImage: `${baseUrl}/cms/cms-bankaccounts/updateBankImage`,
    userList: `${baseUrl}/user/service/UserList`,
    creditBalanceDirect: `${baseUrl}/master/master-transaction/creditBalanceDirect`,
    debitBalanceDirect: `${baseUrl}/master/master-transaction/debitBalanceDirect`,
    updateBalanceRequest: `${baseUrl}/master/master-transaction/updateBalanceRequest`,
    updateCreditLimit: `${baseUrl}/master/master-transaction/updateCreditLimit`,
    updateMarkupList: `${baseUrl}/core/core-markup/updateMarkupList`,
    addB2bCommission: `${baseUrl}/core/core-commission/addB2bCommission`,
    addGdsCommission: `${baseUrl}/core/core-commission/addGdsCommission`,
    b2bCommissionList: `${baseUrl}/core/core-commission/b2bCommissionList`,
    markUpList: `${baseUrl}/core/core-markup/markupList`,
    gdsCommissionList: `${baseUrl}/core/core-commission/gdsCommissionList`,
    deleteB2bCommission: `${baseUrl}/core/core-commission/deleteB2bCommission`,
    deleteMarkup: `${baseUrl}/core/core-markup/deleteMarkup`,
    deleteGdsCommission: `${baseUrl}/core/core-commission/deleteGdsCommission`,
    updateB2bCommission: `${baseUrl}/core/core-commission/updateB2bCommission`,
    commissionList: `${baseUrl}/core/core-commission/commissionList`,
    b2bCarReport: `${baseUrl}/dashboard/report/agentCarReport`,
    b2bFlightVoucher: `${baseUrl}/dashboard/report/flightVoucher`,
    b2bHotelVoucher: `${baseUrl}/dashboard/report/hotelVoucher`,
    b2bCarVoucher: `${baseUrl}/car_enquiry/carVoucher`,
    refreshToken: `${baseUrl}/auth/service/refreshToken`,
    bookingCount: `${baseUrl}/dashboard/report/bookingCount`,
    monthWiseBookingCount: `${baseUrl}/dashboard/report/monthWiseBookingCount`,
    latestMembers: `${baseUrl}/dashboard/report/latestMembers`,
    latestTransactions: `${baseUrl}/dashboard/report/latestTransactions`,
    deleteFlightGroupBooking: `${baseUrl}/flight/group-bookings/deleteFlightGroupBooking`,
    updateFlightGroupBookingStatus: `${baseUrl}/flight/group-bookings/updateFlightGroupBookingStatus`,
    deleteHotelGroupBooking: `${baseUrl}/hotel/group-bookings/deleteHotelGroupBooking`,
    updateHotelGroupBookingStatus: `${baseUrl}/hotel/group-bookings/updateHotelGroupBookingStatus`,
    importPnrList: `${baseUrl}/webservice/flight/importPNR`,
    domainLogo: `${baseUrl}/cms/service/uploadCorporateDomainLogo`,
    paymmentGateway: `${baseUrl}/ws-apis/getWsPaymentGateWays`, // get payment gateway
    paymmentGatewayRequest: `${baseUrl}/ws-apis/updateWsPaymentGateWays`, // update payment gateway request
    updateAirlineList: `${baseUrl}/ws-apis/updateWsBlockAirline`, // update block airline list
    b2cHotelReport: `${baseUrl}/dashboard/report/b2cHotelReport`,
    b2cFlightReport: `${baseUrl}/dashboard/report/b2cFlightReport`,
    b2cCarReport: `${baseUrl}/dashboard/report/b2cCarReport`,
    b2cHotelVoucher: `${baseUrl}/dashboard/report/hotelVoucher`,
    b2cFlightVoucher: `${baseUrl}/dashboard/report/flightVoucher`,
    b2cCarVoucher: `${baseUrl}/dashboard/report/carVoucher`,
    coreHelpdeskList: `${baseUrl}/core/core-helpdesks/coreHelpdeskList`,
    coreRewardList: `${baseUrl}/core/core-rewards/coreRewardList`,
    coreRewardConversion: `${baseUrl}/core/core-reward-conversion/coreRewardConversion`,
    b2cUsersList: `${baseUrl}/user/service/userList`,
    userTypeList: `${baseUrl}/user/service/UserTypeList`,
    userTitleList: `${baseUrl}/user/service/userTitleList`,
    phoneCodeList: `${B2B_URL}/b2b/common/phoneCodeList`,
    addUser: `${baseUrl}/user/service/addUser`,
    deleteUser: `${baseUrl}/user/service/deleteUser`,
    updateUserStatus: `${baseUrl}/user/service/updateUserStatus`,
    countryList: `${baseUrl}/common/CountryList`,
    updateProfile: `${baseUrl}/user/service/updateProfile`,
    uploadUserProfilePhoto: `${baseUrl}/user/service/uploadUserProfilePhoto`,
    getUserById: `${baseUrl}/user/service/getUserById`,
    listPromocode: `${baseUrl}/core/core-promocodes/listPromocode`,
    addPromocode: `${baseUrl}/core/core-promocodes/addPromocode`,
    deletePromocode: `${baseUrl}/core/core-promocodes/deletePromocode`,
    updatePromocode: `${baseUrl}/core/core-promocodes/updatePromocode`,
    uploadPromoImage: `${baseUrl}/core/core-promocodes/uploadPromoImage`,
    emailSubscriptionsList: `${baseUrl}/core/core-subscribed-emails/emailSubscriptionsList`,
    corePaymentChargeList: `${baseUrl}/core/core-payment-charges/corePaymentChargeList`,
    updatePaymentCharge: `${baseUrl}/core/core-payment-charges/updatePaymentCharge`,
    getAllHotelGroupBooking: `${baseUrl}/hotel/group-bookings/getAllHotelGroupBooking`,
    getAllCarGroupBooings: `${baseUrl}/car/group-bookings/getAllCarGroupBooings`,
    getAllFlightGroupBookings: `${baseUrl}/flight/group-bookings/getAllFlightGroupBookings`,
    listFlightTopDestination: `${baseUrl}/flight/flight-top-destinations/listFlightTopDestination`,
    addFlightTopDestination: `${baseUrl}/flight/flight-top-destinations/addFlightTopDestination`,
    uploadFlightTopDestinationImage: `${baseUrl}/flight/flight-top-destinations/uploadFlightTopDestinationImage`,
    updateFlightTopDestination: `${baseUrl}/flight/flight-top-destinations/updateFlightTopDestination`,
    deleteFlightTopDestinationImage: `${baseUrl}/flight/flight-top-destinations/deleteFlightTopDestinationImage`,
    updateFlightTopDestinationStatus: `${baseUrl}/flight/flight-top-destinations/updateFlightTopDestinationStatus`,
    cabinClass: `${B2C_URL}/webservice/flight/cabinClassList`,
    flightAutocomplete: `${B2C_URL}/webservice/flight/autocomplete`,
    //Hotel top destinations
    listHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/listHotelTopDestination`,
    addHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/addHotelTopDestination`,
    uploadHotelTopDestinationImage: `${baseUrl}/hotel/hotel-top-destinations/uploadHotelTopDestinationImage`,
    updateHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/updateHotelTopDestination`,
    deleteHotelTopDestination: `${baseUrl}/hotel/hotel-top-destinations/deleteHotelTopDestination`,
    updateHotelTopDestinationStatus: `${baseUrl}/hotel/hotel-top-destinations/updateHotelTopDestinationStatus`,
    hotelAutocompleteCity: `${B2C_URL}/webservice/hotel/hotel/autoCompleteSmyrooms`,
    //Testimonials
    addTestimonialContent: `${baseUrl}/core/core-static-page-content/addTestimonialContent`,
    updatTestimonialContent: `${baseUrl}/core/core-static-page-content/updatTestimonialContent`,
    deleteTestimonialContent: `${baseUrl}/core/core-static-page-content/deleteTestimonialContentRecords`,
    updateTestimonialContentStatus: `${baseUrl}/core/core-static-page-content/updateTestimonialContentStatus`,
    coreTestimonialContentList: `${baseUrl}/core/core-static-page-content/coreTestimonialContentList`,
    // Discounts/offers
    addDiscountContent: `${baseUrl}/core/core-static-page-content/addDiscountContent`,
    updateDiscountContent: `${baseUrl}/core/core-static-page-content/updateDiscountContent`,
    deleteDiscountContentRecords: `${baseUrl}/core/core-static-page-content/deleteDiscountContentRecords`,
    updateDiscountContentStatus: `${baseUrl}/core/core-static-page-content/updateDiscountContentStatus`,
    coreDiscountContentList: `${baseUrl}/core/core-static-page-content/coreDiscountContentList`,
    getBackAccountDetails: `${baseUrl}/core/core-static-page-content/coreDiscountContentList`,
    b2bHotelReport: `${baseUrl}/dashboard/report/agentHotelReport`,
    trainById:`${baseUrl}/train/findAllByCorporateId`,
    carById:`${baseUrl}/car_enquiry/findAllCorporateById`,
    b2bTrainReport:`${baseUrl}/dashboard/report/agentHotelReport`,
    b2bFlightReport: `${baseUrl}/dashboard/report/agentFlightReport`,
    getAgentLoginAlert: `${baseUrl}/core/core-agent-login-alert/getAgentLoginAlert`,
    addAgentLoginAlert: `${baseUrl}/core/core-agent-login-alert/addAgentLoginAlert`,
    updateAgentLoginAlert: `${baseUrl}/core/core-agent-login-alert/updateAgentLoginAlert`,
    addStaticPageContent: `${baseUrl}/core/core-static-page-content/addStaticPageContent`,
    updateStaticPageContent: `${baseUrl}/core/core-static-page-content/updateStaticPageContent`,
    staticPageContentList: `${baseUrl}/core/core-static-page-content/staticPageContentList`,
    deleteStaticPageContent: `${baseUrl}/core/core-static-page-content/deleteStaticPageContent`,
    sliderSettingsList: `${baseUrl}/core/core-slider-settings/sliderSettingsList`,
    deleteCoreSliderSettings: `${baseUrl}/core/core-slider-settings/deleteCoreSliderSettings`,
    updatCoreSliderSettingStatus: `${baseUrl}/core/core-slider-settings/updatCoreSliderSettingStatus`,
    addSliderSetting: `${baseUrl}/core/core-slider-settings/addSliderSetting`,
    updateCoreSliderSettings: `${baseUrl}/core/core-slider-settings/updateCoreSliderSettings`,
    getModuleTypes: `${B2B_URL}/b2b/common/getModuleTypes`,
    updatCoreStaticPageContentStatus: `${baseUrl}/core/core-static-page-content/updatCoreStaticPageContentStatus`,
    coreHelpdeskAgentName: `${baseUrl}/core/core-helpdesks/coreHelpdeskAgentName`,
    uploadImage: `${baseUrl}/core/core-main-banner-images/uploadImage`,
    mainBannerImagesList: `${baseUrl}/core/core-main-banner-images/mainBannerImagesList`,
    deleteMainBannerImage: `${baseUrl}/core/core-main-banner-images/deleteMainBannerImage`,
    updateMainBannerImage: `${baseUrl}/core/core-main-banner-images/updateMainBannerImage`,
    socialNetwork: `${baseUrl}/core/core-manage-social-links/listManageSocialLink`,
    getPrivilegePageList: `${baseUrl}/core/core-static-page-content/getPrivilegePageList`,
    setUserPrivilege: `${baseUrl}/core/core-static-page-content/setUserPrivilege`,
    getPrivilegedUser: `${baseUrl}/core/core-static-page-content/getPrivilegedUser`,
    revokeParticularPrivilege: `${baseUrl}/core/core-static-page-content/revokeParticularPrivilege`,
    //Added by Asha - Manage API
    manageApiList: `${baseUrl}/ws-apis/getWsApisByModule`,
    manageFlightApiList: `${baseUrl}/flight/flight-service/preferredAirlines`,
    updateApiStatus: `${baseUrl}/ws-apis/updateWsApiStatus`,
    pnrRetrieve: `${B2C_URL}/webservice/flight/pnrRetrieve`,
    checkWalletBalance: `${B2B_URL}/b2b/account-system/checkWalletBalance`,
    deductFromWallet: `${B2B_URL}/b2b/account-system/deductFromWallet`,
    sendToAllSubscribers: `${B2B_URL}/b2b/common/sendToAllSubscribers`,
    addAirlineHotelPartnerImage: `${baseUrl}/core/core-airline-hotel-partners/addAirlineHotelPartnerImage`,
    deleteAirlineHotelPartnerImage: `${baseUrl}/core/core-airline-hotel-partners/deleteAirlineHotelPartnerImage`,
    updateAirlineHotelPartnerStatus: `${baseUrl}/core/core-airline-hotel-partners/updateAirlineHotelPartnerStatus`,
    airlineHotelPartnerList: `${baseUrl}/core/core-airline-hotel-partners/airlineHotelPartnerList`,
    updateAirlineHotelPartnerContent: `${baseUrl}/core/core-airline-hotel-partners/updateAirlineHotelPartnerContent`,
    cancelFlightBooking: `${B2C_URL}/webservice/flight/cancellation`,
    voidFlightBooking: `${B2C_URL}/webservice/flight/void`,
    importPnr: `${B2C_URL}/webservice/flight/importPNR`,
    //Update last ticketing time api's
    updateLastTicketingTime: `${baseUrl}/flight/flight-service/updateLastTicketingTime`,
    getLastTicketingUpdatedTime: `${baseUrl}/flight/flight-service/getAirLineList`,
    updateCreditLimitDirect:`${baseUrl}/master/master-transaction/updateCreditLimitDirect`,
    stateList:`${baseUrl}/common/hotelStates`,
    addCostCenter:`${baseUrl}/master/master-cost-center/create`,
    updateCostCenter:`${baseUrl}/master/master-cost-center/update`,
    getCostCenter:`${baseUrl}/master/master-cost-center/findAll`,
    deleteCostCenter:`${baseUrl}/master/master-cost-center/delete`,
    uploadCSV:`${baseUrl}/master/master-cost-center/upload-create-file`,
    addDepartment:`${baseUrl}/master/master-department/create`,
    updateDepartment:`${baseUrl}/master/master-department/update`,
    getDepartment:`${baseUrl}/master/master-department/findAll`,
    deleteDepartment:`${baseUrl}/master/master-department/delete`,
    uploadDepartmentCSV:`${baseUrl}/master/master-department/upload-create-file`,
    addPurpose:`${baseUrl}/master/master-purpose/create`,
    updatePurpose:`${baseUrl}/master/master-purpose/update`,
    getPurpose:`${baseUrl}/master/master-purpose/findAll`,
    deletePurpose:`${baseUrl}/master/master-purpose/delete`,
    uploadPurposeCSV:`${baseUrl}/master/master-purpose/upload-create-file`,
    addPosition:`${baseUrl}/master/master-position/create`,
    updatePosition:`${baseUrl}/master/master-position/update`,
    getPosition:`${baseUrl}/master/master-position/findAll`,
    deletePosition:`${baseUrl}/master/master-position/delete`,
    uploadPositionCSV:`${baseUrl}/master/master-position/upload-create-file`,
    addEmployee:`${baseUrl}/master/master-employee/create`,
    updateEmployee:`${baseUrl}/master/master-employee/update`,
    getEmployee:`${baseUrl}/master/master-employee/findAll`,
    getApprovalList:`${baseUrl}/master/master-employee/find`,
    deleteEmployee:`${baseUrl}/master/master-employee/delete`,
    uploadEmployeeCSV:`${baseUrl}/master/master-employee/upload-create-file`,
    getPolicyList:`${baseUrl}/policy/findAll`,
    deletePolicy:`${baseUrl}/policy/delete`,
    addPolicy:`${baseUrl}/policy/create`,
    updatePolicy:`${baseUrl}/policy/update`,
    getCity:`${baseUrl}/common/city/findAll`,
    addIcicCity:`${baseUrl}/icicCityList/create`,
    updateCity:`${baseUrl}/icicCityList/update`,
    getIcicCity:`${baseUrl}/icicCityList/findAll`,
    deleteCity:`${baseUrl}/icicCityList/delete`,
    addLocation:`${baseUrl}/icicCityLocationList/create`,
    getLocation:`${baseUrl}/icicCityLocationList/findAll`,
    updateLocation:`${baseUrl}/icicCityLocationList/update`,
    deleteLocation:`${baseUrl}/icicCityLocationList/delete`,
    addHotelList:`${baseUrl}/icicHotelList/create`,
    getHotelList:`${baseUrl}/icicHotelList/findAll`,
    updateHotelList:`${baseUrl}/icicHotelList/update`,
    deleteHotelList:`${baseUrl}/icicHotelList/delete`,
    addGuestHouseList:`${baseUrl}/icicGuestHouseList/create`,
    getGuestHouseList:`${baseUrl}/icicGuestHouseList/findAll`,
    updateGuestHouseList:`${baseUrl}/icicGuestHouseList/update`,
    deleteGuestHouseList:`${baseUrl}/icicGuestHouseList/delete`,
    uploadCityCSV:`${baseUrl}/icicCityList/upload-create-file`,
    uploadLocationCSV:`${baseUrl}/icicCityLocationList/upload-create-file`,
    uploadHotelCSV:`${baseUrl}/icicHotelList/upload-create-file`,
    uploadGuestHouseCSV:`${baseUrl}/icicGuestHouseList/upload-create-file`,
    cityLocationList:`${baseUrl}/icicCityLocationList/findAllLocationByCitycode`,
    findAllCity:`${baseUrl}/icicCityList/findAllCity`,
    trainFindAll:`${baseUrl}/train/findAll`,
    hotelMisDownloadData:`${baseUrl}/hotel/hotels/misHotelBooking`,
    trainingName:`${baseUrl}/trainingName/create`,
    trainingFindAll:`${baseUrl}/trainingName/findAll`,
    deleteTrainingName:`${baseUrl}/trainingName/delete`,
    trainingVenue:`${baseUrl}/trainingVenue/create`,
    trainingVenueFindAll:`${baseUrl}/trainingVenue/findAll`,
    deleteTrainingVenue:`${baseUrl}/trainingVenue/delete`,
    trainerName:`${baseUrl}/trainerName/create`,
    trainerNameFindAll:`${baseUrl}/trainerName/findAll`,
    deleteTrainerName:`${baseUrl}/trainerName/delete`,
    trainingDetailsFindAll:`${baseUrl}/trainingDetails/findAll`,
    getTrainingDetails:`${baseUrl}/trainingDetails/getTrainingDetails`,
    airportList: `${B2C_URL}/webservice/flight/autocomplete`,
    autoCompleteCrs:`${baseUrl}/common/CityListDcb`,
    carFindAll:`${baseUrl}/car_enquiry/findAll`,
    trainVoucher:`${baseUrl}/train/trainVoucher`, 
    flightMis:`${baseUrl}/dashboard/report/flightMISReport`,
    employeeApproval: `${baseUrl}/employee-approval/create`,
    updateEmployeeApproval: `${baseUrl}/employee-approval/update`,
    approvalList:`${baseUrl}/employee-approval/findAll`,
    deleteEmployeeApproval:`${baseUrl}/employee-approval/delete`,
    busReport:`${baseUrl}/dashboard/report/AgentBusReport`,
    busVoucher: `${B2C_URL}/webservice/bus/bus/voucher`,
    balanceRequestListAccountSys: `${baseUrl}/account-system/balanceRequestList`,
    getRequestTypes: `${baseUrl}/common/getRequestTypes`,
    getPaymentModes: `${baseUrl}/common/getPaymentModes`,
    balanceRequestAccountSys: `${baseUrl}/account-system/balanceRequest`,
    listBankAccountAccountSys: `${baseUrl}/cms/cms-bankaccounts/listBankAccount`,
    setBalanceAlertAccountSys: `${baseUrl}/account-system/setBalanceAlert`,
    updateBalanceAlertAccountSys: `${baseUrl}/account-system/updateBalanceAlert`,
    creditLimitRequestAccountSys: `${baseUrl}/account-system/creditLimitRequest`,
    flightReports: `${baseUrl}/reports/flightReport`,
    hotelReports: `${baseUrl}/reports/hotelReport`,
    getAgentById: `${baseUrl}/user/service/getAgentById`,
    accountLedgerAccountSys: `${baseUrl}/account-system/accountLedger`,
    universityCreate: `${baseUrl}/master/master-university/create`,
    universitiesList: `${baseUrl}/master/master-university/findAll`,
    universityUpdate: `${baseUrl}/master/master-university/update`,
    courseTypeCreate: `${baseUrl}/master/master-course-type/create`,
    courseTypeList: `${baseUrl}/master/master-course-type/findAll`,
    courseTypeUpdate: `${baseUrl}/master/master-course-type/update`,
    courseNameCreate: `${baseUrl}/master/master-course/create`,
    courseNameList: `${baseUrl}/master/master-course/findAll`,
    courseNameUpdate: `${baseUrl}/master/master-course/update`,
    studentRegistration: `${baseUrl}/master/master-student/create`,
    studentRegistrationList: `${baseUrl}/master/master-student/findAll`,
};
